In [1]:
import numpy as np

start = 10
end = 34
array = np.arange(start, end).reshape(8, 3)

print("Creating 8X3 array")
print(array)

sub_arrays = np.array_split(array, 4)

print("\nDividing 8X3 array into 4 sub array")
print(sub_arrays)

Creating 8X3 array
[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]]

Dividing 8X3 array into 4 sub array
[array([[10, 11, 12],
       [13, 14, 15]]), array([[16, 17, 18],
       [19, 20, 21]]), array([[22, 23, 24],
       [25, 26, 27]]), array([[28, 29, 30],
       [31, 32, 33]])]
