In [9]:
import numpy as np
a=[1,2,3,4,5,6]
a

[1, 2, 3, 4, 5, 6]

In [8]:
#creating numpy array 
x=np.array(a)
x

array([1, 2, 3, 4, 5, 6])

In [39]:
# first is row next is col
a=np.array([[1,2,3,],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
#passing array inside array
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a# direct reference for the print 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
#shape attribute return shape of an array 
a.shape

(3, 3)

In [17]:
#size returns total number of elements in an array 
a.size

9

In [18]:
#ndim give how many dimension of the array i.e it counts the square bracket in 2-3 dimension array
a.ndim

2

In [19]:
#transpose c0nvert row into col viz
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [29]:
#function reshape change shape of an array make sure product should 
a=a.reshape(9,6)
a

ValueError: cannot reshape array of size 9 into shape (9,6)

In [44]:
b=np.array([11,12,13,14,15,16])
b=b.reshape(2,3)
b


array([[11, 12, 13],
       [14, 15, 16]])

In [47]:
#concantenate join two array
np.concatenate((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16]])

In [45]:
#vstack join two array vertically (col)
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16]])

In [46]:
#hstack join two array horizontal(row)
np.hstack((a,b))

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16]])

In [50]:
#append -- used to add element in an array only at the end 
c=np.array([21,22,23,25,26])
c
c=np.append(c,[27,28,29,30]) # c is the array to be updated 
c

array([21, 22, 23, 25, 26, 27, 28, 29, 30])

In [51]:
#insert add ele at specified index 
c=np.insert(c,3,24) #which array at what index which value 
c


array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [53]:
#delete delete any ele from array
c=np.delete(c,[9]) # which array, from what index
c

array([21, 22, 23, 24, 25, 26, 27, 28, 29])

In [62]:
#arrange it creates an array with given size 
#slicing single dim array
#x=np.arange(6)
#x
#y=np.arange(2,30,2) # 2 to 30 with diff of 2
#y
#y=y.reshape(7,2)
#y
y[0:4]

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

In [65]:
## random.rand:  create array with random number(float) of specifies size
import numpy as np
#np.random.rand(4) #1d array with 4 array
#np.random.randn(4) #this will show negative val as well
#np.random.randn(2,3) #2d array with 2 row and 3 col 
np.random.randn(3,2,3) # 3D array with 3 matrix of 2 rows and 3 cols

array([[[-3.1746372 , -0.5095073 , -0.37907668],
        [-0.70540288,  0.05300758,  1.39596439]],

       [[-1.3458707 ,  0.90030753,  0.90999274],
        [-1.02042372, -0.22641498,  0.056825  ]],

       [[ 0.28333229, -0.79440483, -0.51957342],
        [-1.35320087,  1.76432864,  0.57975739]]])

In [1]:
#sum of the all elements
a.sum()

NameError: name 'a' is not defined

In [3]:
import numpy as np
a=np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#aggregate function 

In [11]:
#find the sum of all numbers
a=a.sum()
a

np.int64(55)

In [5]:
#find prod of all elements
a.prod()

np.int64(3628800)

In [6]:
#find all the mean value from all elements
a.mean()

np.float64(5.5)

In [49]:
#std find standard deviation from all values 
b=np.arange(2,22,2)
b=b.reshape(2,5)

b.std()

np.float64(5.744562646538029)

In [35]:
#find the variance 
b.var()

np.float64(33.0)

In [36]:
print(b.min())
print(b.max())

2
20


In [39]:
#checks if all array elements along a given axis evaulate to true all non zero value 
b.all()

np.True_

In [44]:
b=np.zeros((10,10))
b
b.all()

np.False_

In [47]:
import numpy as np

# Create an array of even numbers from 2 to 20
b = np.arange(2, 22, 2)

# Reshape the array to a shape of (2, 5)
b = b.reshape(2, 5)

# Calculate the standard deviation of the array
std_dev = b.std()#std here stands for standard deviation 

print(b)
print("Standard Deviation:", std_dev)


[[ 2  4  6  8 10]
 [12 14 16 18 20]]
Standard Deviation: 5.744562646538029


In [50]:
c=np.eye(3)
c.any()

np.True_

In [53]:
d=np.eye(3,3,k=0)
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [69]:
b=np.zeros((3,2))
#b1=b.shape[1]

#print(b1)
for i in range(2):
    b[i]=i

b=b.T
b=b.shape[1]
print(b1) # no of values in col index 1 

10


In [71]:
#running totol
#cumsum() -- returns the cumilative sum of the elements along a given matrix
b=np.arange(2,22,2)
b=b.reshape(2,5)
print(b)
b.cumsum()# running total oall elal

[[ 2  4  6  8 10]
 [12 14 16 18 20]]


array([  2,   6,  12,  20,  30,  42,  56,  72,  90, 110])

In [ ]:
vectorization -- it refers to performing elemen ts wise operation on array
it saves excution time interview main

In [72]:
import numpy as np
array1 = np.array([1, 2, 3, 4, 5 ])
number = 10

#  number sums up with each array element
result = array1 + number

print(result)
print(type(result))

[11 12 13 14 15]
<class 'numpy.ndarray'>


In [73]:
import time 

start = time.time()

array1 = [1, 2, 3, 4, 5]

for i in range(len(array1)):
    array1[i] =array1[i]+ 10

#print(array1)

end = time.time()

print("For loop time:", end - start)

For loop time: 0.0


In [75]:
import numpy as np
import time

start = time.time()

array1 = np.array([1, 2, 3, 4, 5 ])

result = array1 + 10

#print(result)

end = time.time()

print("Vectorization time:", end - start)


Vectorization time: 0.0


In [78]:
# find square of number in an array
import time
start_time= time.time()
def find_square(x):
    if x < 0:
        return 0
    else:
        return x ** 2


#s=find_square(4)
#s
array1 = [1, 2, 3, 4, 5]
v_func=np.vectorize(find_square)
s=v_func(array1)

print(s)

end_time= time.time()

print("total execution time is",end_time-start_time)

total execution time is 0.0010013580322265625


In [79]:
#campatibility rules: one of them has a length of 1 or they are equal
#check from right to left
x=np.arange(2,22,2)

#print(x)

y=np.arange(30,40)

w=np.arange(2)

x=x.reshape(2,5)

#y=y.reshape(5,2)  # cannot broadcast
#y=y.reshape(10,1)  # cannot broadcast
y=y.reshape(2,5)

#w=w.reshape(1,2)  #cannot broadcast
w=w.reshape(2,1)
print(w)
z=x+y+w
z

[[0]
 [1]]


array([[32, 35, 38, 41, 44],
       [48, 51, 54, 57, 60]])

In [80]:
a=np.array([23,56,88,1,2,4,10,15])
# boolean mask
bm=a>40
print(bm)
print(a[bm])


[False  True  True False False False False False]
[56 88]
